// Generated by CoffeeScript 1.4.0
(function() {
  var _this = this;

  this.GlassHouse = {
    load: function(options) {
      this.formEl = $("#" + options.formId);
      this.formEl.jsonForm({
        form: this.form,
        schema: this.schema
      });
      return this;
    },
    loadAxioms: function(name) {
      return $.ajax({
        url: "glasshouse/plants/" + name + ".json",
        dataType: "text"
      }).done(function(code) {
        var aceId, editor;
        aceId = $("#form .ace_editor").attr("id");
        editor = ace.edit(aceId);
        return editor.getSession().setValue(GlassHouse.render(code));
      });
    },
    render: function(code) {
      console.log(code[code.length - 1]);
      return "Lima.load(" + code + ")" + ".iterate(3)\n" + ".run('canvas',\n" + "     {step: 10,\n" + "      origin: function(w,h) {\n" + "        return {x: w/2,\n" + "                y: h/2,\n" + "                angle: 90};\n" + "        }\n" + "      });";
    },
    run: function() {
      var code;
      code = this.formEl.jsonFormValue().console;
      return eval(code);
    },
    form: [
      {
        key: "axioms",
        notitle: true,
        titleMap: {
          basic: "spinning ivy",
          dragon: "the classical dragon fractal"
        },
        htmlClass: "trywith",
        onChange: function(e) {
          var selected;
          selected = $(e.target).val();
          return GlassHouse.loadAxioms(selected);
        }
      }, {
        key: "console",
        type: "ace",
        width: "100%",
        height: window.innerHeight + 'px',
        notitle: true,
        onChange: function(e) {
          return GlassHouse.run();
        }
      }
    ],
    schema: {
      axioms: {
        title: "axioms to load",
        type: "string",
        "enum": ["dragon", "basic"],
        "default": "basic"
      },
      console: {
        title: "load or edit axioms",
        type: "string"
      }
    }
  };

}).call(this);
