// Generated by CoffeeScript 1.4.0
(function() {

  this.Lima = {};

  Lima.load = function(options) {
    var lsys;
    lsys = new Lima.LSys(options);
    return new Lima.ProcessingSetup(lsys);
  };

}).call(this);
