// Generated by CoffeeScript 1.4.0
(function() {

  Lima.ProcessingSetup = (function() {

    function ProcessingSetup(lsys) {
      console.log("boot");
      this.lsys = lsys;
      this.frames = 100;
      this.bColor = 200;
    }

    ProcessingSetup.prototype.iterate = function(times) {
      this.iterations = times;
      return this;
    };

    ProcessingSetup.prototype.run = function(canvasId, options) {
      this.w = options.width || $(document).width();
      this.h = options.height || $(document).height();
      this.iterations || (this.iterations = 10);
      this.procInstance = new Processing(canvasId, this.processingSetup());
      return this;
    };

    ProcessingSetup.prototype.processingSetup = function() {
      var _this = this;
      this.lsys.iterate(this.iterations);
      console.log(this.lsys);
      this.cursor = 0;
      return function(p) {
        _this.t = new Lima.Turtle(p, {
          x: _this.w / 2,
          y: _this.h / 2,
          angle: 90
        });
        p.setup = function() {
          return _this.setup.call(_this, p);
        };
        p.draw = function() {
          return _this.draw.call(_this, p);
        };
        return null;
      };
    };

    ProcessingSetup.prototype.draw = function(p) {
      if (this.cursor > this.lsys.length - 1) {
        return;
      }
      this.lsys.draw(this.cursor, this.t);
      return this.cursor++;
    };

    ProcessingSetup.prototype.setup = function(p) {
      p.size(this.w, this.h);
      p.frameRate(this.frames);
      return p.background(0, 0, 1, .5);
    };

    return ProcessingSetup;

  })();

}).call(this);
